import { describe, it, expect } from 'vitest';
import { configSchema } from '../../src/core/config-schema.js';

describe('Config Schema', () => {
  it('should validate valid configuration', () => {
    const validConfig = {
      projectName: 'test-project',
      structure: {
        type: 'atomic' as const,
        paths: {
          atoms: 'src/components/atoms',
          molecules: 'src/components/molecules'
        }
      },
      stack: ['React', 'TypeScript', 'TailwindCSS'],
      detection: {
        enabled: true,
        watchPatterns: ['src/**/*.tsx'],
        autoGenerateDocs: true
      }
    };

    const result = configSchema.parse(validConfig);
    expect(result.projectName).toBe('test-project');
    expect(result.structure.type).toBe('atomic');
    expect(result.stack).toContain('React');
  });

  it('should validate config with AI provider', () => {
    const configWithAI = {
      projectName: 'test-project',
      structure: {
        type: 'feature-based' as const,
        paths: { features: 'src/features' }
      },
      stack: ['Next.js'],
      ai: {
        provider: 'claude' as const,
        model: 'claude-3-5-sonnet-20241022',
        apiKey: 'sk-test-key'
      },
      detection: {
        enabled: true,
        watchPatterns: ['app/**/*.tsx'],
        autoGenerateDocs: true
      }
    };

    const result = configSchema.parse(configWithAI);
    expect(result.ai).toBeDefined();
    expect(result.ai?.provider).toBe('claude');
    expect(result.ai?.model).toBe('claude-3-5-sonnet-20241022');
  });

  it('should reject invalid structure type', () => {
    const invalidConfig = {
      projectName: 'test',
      structure: {
        type: 'invalid-type',
        paths: {}
      },
      stack: [],
      detection: {
        enabled: true,
        watchPatterns: [],
        autoGenerateDocs: true
      }
    };

    expect(() => configSchema.parse(invalidConfig)).toThrow();
  });

  it('should reject missing required fields', () => {
    const incompleteConfig = {
      projectName: 'test'
      // Missing structure and detection
    };

    expect(() => configSchema.parse(incompleteConfig)).toThrow();
  });

  it('should apply default values', () => {
    const minimalConfig = {
      projectName: 'test',
      structure: {
        type: 'atomic' as const,
        paths: {}
      },
      stack: [],
      detection: {
        watchPatterns: []
        // enabled and autoGenerateDocs should default
      }
    };

    const result = configSchema.parse(minimalConfig);
    expect(result.detection.enabled).toBe(true);
    expect(result.detection.autoGenerateDocs).toBe(true);
  });
});
