/**
 * Config Schema
 *
 * Zod schema for validating anchor.config.json
 * Defines the complete structure and validation rules for CodeAnchor configuration
 */

import { z } from 'zod';

/**
 * Component naming and style rules
 */
export const componentRulesSchema = z.object({
  naming: z.enum(['PascalCase', 'kebab-case']).describe('Component naming convention'),
  fileNaming: z.enum(['PascalCase', 'kebab-case']).describe('Component file naming convention'),
  exportStyle: z.enum(['named', 'default']).describe('Export style for components'),
  propsInterface: z.enum(['required', 'optional']).describe('Props interface naming requirement')
}).optional();

/**
 * Styling rules and restrictions
 */
export const stylingRulesSchema = z.object({
  allowed: z.array(z.string()).describe('Allowed styling approaches'),
  banned: z.array(z.string()).optional().describe('Banned styling approaches')
}).optional();

/**
 * Code standards and rules
 */
export const rulesSchema = z.object({
  components: componentRulesSchema,
  styling: stylingRulesSchema
}).optional();

/**
 * AI provider configuration
 */
export const aiConfigSchema = z.object({
  provider: z.enum(['claude', 'openai', 'gemini', 'ollama']).describe('AI provider name'),
  model: z.string().describe('Model identifier (e.g., claude-3-5-sonnet-20241022)'),
  apiKey: z.string().describe('API key for the provider'),
  options: z.object({
    temperature: z.number().min(0).max(1).optional().describe('Sampling temperature'),
    maxTokens: z.number().positive().optional().describe('Maximum tokens per request')
  }).optional()
}).optional().describe('AI configuration (optional for template-only mode)');

/**
 * Project structure configuration
 */
export const structureSchema = z.object({
  type: z.enum(['atomic', 'feature-based', 'modular', 'custom']).describe('Project structure type'),
  paths: z.record(z.string()).describe('Component path mappings')
});

/**
 * Component detection configuration
 */
export const detectionSchema = z.object({
  enabled: z.boolean().default(true).describe('Enable automatic component detection'),
  watchPatterns: z.array(z.string()).describe('Glob patterns to watch for changes'),
  ignore: z.array(z.string()).optional().describe('Patterns to ignore'),
  autoGenerateDocs: z.boolean().default(true).describe('Auto-generate docs on detection')
});

/**
 * Documentation preferences
 */
export const documentationSchema = z.object({
  language: z.enum(['en', 'vi', 'both']).default('en').describe('Documentation language'),
  includeUsageExamples: z.boolean().default(true).describe('Include usage examples in docs')
}).optional();

/**
 * Git integration settings
 */
export const gitSchema = z.object({
  conventionalCommits: z.boolean().default(true).describe('Use conventional commits'),
  autoStageDocs: z.boolean().default(true).describe('Auto-stage generated docs')
}).optional();

/**
 * Main configuration schema
 */
export const configSchema = z.object({
  projectName: z.string().describe('Project name'),
  structure: structureSchema,
  stack: z.array(z.string()).describe('Tech stack (React, Next.js, TailwindCSS, etc.)'),
  rules: rulesSchema,
  ai: aiConfigSchema,
  detection: detectionSchema,
  documentation: documentationSchema,
  git: gitSchema
});

/**
 * Inferred TypeScript type from schema
 */
export type AnchorConfig = z.infer<typeof configSchema>;

/**
 * Partial config for initial setup
 */
export type PartialAnchorConfig = Partial<AnchorConfig> & {
  projectName: string;
  structure: z.infer<typeof structureSchema>;
  detection: z.infer<typeof detectionSchema>;
};
